# Generated by Django 5.0.3 on 2024-03-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_idf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
