# Generated by Django 5.0.3 on 2024-03-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_idf', '0003_remove_words_idf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='tf',
            field=models.FloatField(),
        ),
    ]
