# Generated by Django 5.0.3 on 2024-03-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tf_idf', '0004_alter_words_tf'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='itf',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
